pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: /Users/jf3375/PycharmProjects/Speech_Recognition_Diarization_Docker/models/Pyannote/Embedding/pytorch_model.bin
    embedding_batch_size: 32
    embedding_exclude_overlap: true
    segmentation: /Users/jf3375/PycharmProjects/Speech_Recognition_Diarization_Docker/models/Pyannote/VoiceActivityDetection/pytorch_model.bin
    segmentation_batch_size: 32

params:
  clustering:
    method: centroid
    min_cluster_size: 15
    threshold: 0.7153814381597874
  segmentation:
    min_duration_off: 0.5817029604921046
    threshold: 0.4442333667381752
